version: "3.8"
services:
  db:
    container_name: "mulive-db"
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - pg_um_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  # User Management Service:
  # Responsible for persistent features of the game (ex. players' user profiles, progress, history, score)
  umserver:
    container_name: "mulive-umserver"
    build:
      context: ./MuLiveUM
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JDBC_DATASOURCE_URL: "${JDBC_DATASOURCE_URL}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      MULIVE_GAMESERVER_SECRET_HEADER: "${MULIVE_GAMESERVER_SECRET_HEADER}"
      MULIVE_GAMESERVER_SECRET_HEADER_VAL: "${MULIVE_GAMESERVER_SECRET_HEADER_VAL}"

  # Game Server Service:
  # Responsible for handling real-time communication with clients based on game logic
  gameserver:
    container_name: "mulive-gameserver"
    build:
      context: ./MuLiveGameServer
      dockerfile: Dockerfile
    ports:
      - "45600:45600"
    environment:
      MULIVE_GAMESERVER_SECRET_HEADER: "${MULIVE_GAMESERVER_SECRET_HEADER}"
      MULIVE_GAMESERVER_SECRET_HEADER_VAL: "${MULIVE_GAMESERVER_SECRET_HEADER_VAL}"

volumes:
  pg_um_data:
    name: "pg_um_data"