# DB related
spring.datasource.url=jdbc:postgresql://db:5432/mulive
spring.datasource.username=postgres
spring.datasource.password=root!238Ji*
spring.jpa.hibernate.ddl-auto=none

# MuLive related
mulive.gameserver.secret.key=&<yDuTf;$]lmYrgleaL+Na@%Lg8KA(Kr!F_-B:ZbmGR1sa]phygge#9nL089XcG: